# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zulucal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrelation',
            name='firstEventId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='zulucal.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrelation',
            name='secondEventId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='zulucal.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventrelation',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
