# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zulucal', '0004_auto_20170604_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='baseCalendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='zulucal.Calendar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='zulucal.Calendar'),
        ),
    ]
