# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zulucal', '0006_auto_20170604_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('panoculus', models.URLField(default='https://library.panocul.us/mw/index.php?title=Main_Page')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='thing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='zulucal.Thing'),
            preserve_default=False,
        ),
    ]
