# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-13 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zulucal', '0007_auto_20171128_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='panoculus',
            field=models.URLField(default='https://library.panocul.us/mw/index.php/History'),
        ),
        migrations.AlterField(
            model_name='person',
            name='panoculus',
            field=models.URLField(default='https://library.panocul.us/mw/index.php/People'),
        ),
        migrations.AlterField(
            model_name='place',
            name='panoculus',
            field=models.URLField(default='https://library.panocul.us/mw/index.php/Geography'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='panoculus',
            field=models.URLField(default='https://library.panocul.us/mw/index.php/Technology_and_Materials'),
        ),
    ]
