# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-13 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zulucal', '0008_auto_20180512_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='calendarOffset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='earliest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='latest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='pinned',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='eventrelation',
            name='intervalMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventrelation',
            name='intervalMin',
            field=models.IntegerField(default=0),
        ),
    ]
